#!/bin/bash
mkdir -p tests/cases

if [ ! -f ./tests/run ];then
    curl https://raw.githubusercontent.com/tumf/ansible-role-test-init/master/ansible-role-test-run > ./tests/run 2>&1
    chmod +x ./tests/run
fi

if [ ! -f ./tests/hosts ];then
    echo "127.0.0.1" > ./tests/hosts
fi

if [ ! -f ./tests/test.yml ];then
    cat >./tests/test.yml <<EOF
---
- hosts: 127.0.0.1
  connection: local
  tags:
    - default
  roles:
    - role: ../..
EOF
fi


if [ ! -f ./travis.yml ];then
    cat >.travis.yml <<EOF
language: python
python:
- '2.7'
install:
- pip install ansible
before_script:
- ansible --version
- ansible-playbook --syntax-check ./tests/test.yml -i ./tests/hosts
script:
- ./tests/run
EOF
fi

if ! grep '^prefix_dir:' defaults/main.yml >/dev/null 2>&1;then
    echo 'prefix_dir: ""' >>defaults/main.yml
    echo 'Add `prefix_dir: ""`'
fi

if ! grep '^ansible_unit_test:' defaults/main.yml >/dev/null 2>&1;then
    echo 'ansible_unit_test: false' >>defaults/main.yml
    echo 'Add `ansible_unit_test: false`'
fi

if ! grep '^/tests/outputs' .gitignore >/dev/null 2>&1;then
    echo '/tests/outputs' >>.gitignore
    echo 'Add `/tests/outputs`'
fi
