#!/bin/bash
mkdir -p tests/cases

if [ ! -f ./tests/run ];then
    curl -s https://raw.githubusercontent.com/tumf/ansible-unit-test/master/ansible-role-test-run > ./tests/run
    chmod +x ./tests/run
    echo 'Put ./tests/run' >&2
fi

if [ ! -f ./tests/test.yml ];then
    cat >./tests/test.yml <<EOF
---
- hosts: 127.0.0.1
  connection: local
  tags:
    - install
  roles:
    - role: ../..
  tasks:
    - debug: msg="The test case is succeeded."
EOF
    echo 'Put ./tests/test.yml' >&2
fi


if [ ! -f ./travis.yml ];then
    cat >.travis.yml <<EOF
language: python
python:
- '2.7'
install:
- pip install ansible
before_script:
- ansible --version
- cd tests; ansible-playbook --syntax-check ./test.yml -i 127.0.0.1,
script:
- cd tests;./run
EOF
    echo 'Put .travis.yml' >&2
fi

if ! grep '^ansible_unit_test_prefix_dir:' defaults/main.yml >/dev/null 2>&1;then
    echo 'ansible_unit_test_prefix_dir: ""' >>defaults/main.yml
    echo 'Add `ansible_unit_test_prefix_dir: ""` to defaults/main.yml' >&2
fi

if ! grep '^ansible_unit_test:' defaults/main.yml >/dev/null 2>&1;then
    echo 'ansible_unit_test: false' >>defaults/main.yml
    echo 'Add `ansible_unit_test: false` to defaults/main.yml' >&2
fi

if ! grep '^/tests/outputs' .gitignore >/dev/null 2>&1;then
    echo '/tests/outputs' >>.gitignore
    echo 'Add `/tests/outputs` to .gitignore' >&2
fi
